name: Generate coverage badges

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"
    types: 
      - closed

jobs:
  badges:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: gh-pages

      - name: Download artifact
        id: download
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          pr: ${{github.event.pull_request.number}}
          name: coverage-report
          path: ./

      - name: run genbadge
        run: |
          pip install genbadge[all]
          genbadge coverage

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'
