name: Generate coverage badges

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "master"
    types: 
      - closed

jobs:
  badges-coverage:
    #if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: gh-pages

      - name: Download coverage artifact
        id: download-coverage
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          pr: ${{github.event.pull_request.number}}
          name: coverage-report
          path: reports/coverage

      - name: Download flake8 artifact
        id: download-flake
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          pr: ${{github.event.pull_request.number}}
          name: flake8stats.txt
          path: reports/flake8stats

      - name: Run genbadge
        run: |
          ls -R
          pip install genbadge[all]
          genbadge coverage --output-file .github/badges/coverage.svg
          genbadge flake8 --output-file .github/badges/flake8stats.svg

      - name: Commit and push the badges
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badges'
          add: '*.svg'
