name: "PR check"
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test with pytest
        run: |
          pip install pytest
          pytest test

  run-flake8-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

#      - name: flake8 Lint
#        uses: py-actions/flake8@v2
#        with:
#          max-line-length: "130"
      - name: flake8 report
        run: |
          python3.11 -m pip install flake8
          flake8 -vv --output-file=flake8.txt ./reports/flake8/
      - name: flake8 art ls
        run: |
          ls -R
          
      - name: Upload flake8 report
        uses: actions/upload-artifact@v4
        with:
          name: flake8stats.txt
          path: ./reports/flake8/


  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.11'
        coverage:
          - '7.5'
    name: Python ${{ matrix.python }} on coverage ${{ matrix.coverage }}
    steps:
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Get repository code
        uses: actions/checkout@v4

      - name: Collect coverage
        run: | 
          pip install coverage pytest
          coverage run --source=./src -m unittest discover 
          coverage xml -o coverage.xml

      - name: Coverage report
        run: coverage report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
