name: "PR check"
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  
jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - run:
          pip install flake8 flake8-import-order sphinx sphinx_rtd_theme
          rstcheck[sphinx] doc8
      - run: pip install .
      - run: flake8 .
      - run: doc8 $(git ls-files '*.rst')
      - run: rstcheck --ignore-directives automodule $(git ls-files '*.rst')
      - run: yamllint --strict $(git ls-files '*.yaml' '*.yml')
      - run: make -C docs html
      - name: Check for broken links in documentation
        run: make -C docs linkcheck
