name: demo chek
on: [merge_group, workflow_dispatch]
jobs:
  chek_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test