name: "PR check"
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test

  run-flake8-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "130"

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.11'
        coverage:
          - '7.5'
    name: Python ${{ matrix.python }} on coverage ${{ matrix.coverage }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges [skip ci]"
          branch: gh-pages
          skip_fetch: true
          skip_checkout: true
          
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Collect coverage
        run: | 
          pip install coverage pytest
          coverage run --source=./src -m unittest discover
      - name: Make coverage JSON
        run: coverage json && ls -la
