name: "symbol_checker"
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check with yml
        run: |
         symbol_checker.py --input_dir=/.github/workflows --mask=*.yml --recursive
